# Generated by Django 6.0.2 on 2026-03-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(blank=True, max_length=10, null=True)),
                ('reference', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], default='EMAIL', max_length=10)),
                ('event_type', models.CharField(max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
