# Generated by Django 6.0.2 on 2026-03-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='ucgsi438847284', max_length=100),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(default='445275129', max_length=10, unique=True),
        ),
    ]
