# Generated by Django 6.0.2 on 2026-03-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_transaction_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.CharField(default='cxqli686947805', max_length=100),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(default='4424744504', max_length=10, unique=True),
        ),
    ]
