# Generated by Django 6.0.2 on 2026-02-27 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(default='4431766340', max_length=10, unique=True),
        ),
    ]
