# Generated by Django 6.0.2 on 2026-02-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_wallet_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(default='4498701726', max_length=10, unique=True),
        ),
    ]
