# Generated by Django 6.0.2 on 2026-02-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallet_updated_at_alter_wallet_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(default='4423377542', max_length=10, unique=True),
        ),
    ]
