# Generated by Django 6.0.2 on 2026-03-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_wallet_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='account_number',
            field=models.CharField(default='4450049074', max_length=10, unique=True),
        ),
    ]
